# Copyright (c) 2025 Preston Elder
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

"""Constants for Power Pet Door integration."""

# Re-export all protocol constants from the library
from powerpetdoor.const import (
    # Timing
    MINIMUM_TIME_BETWEEN_MSGS,
    # Message types
    COMMAND,
    CONFIG,
    PING,
    PONG,
    DOOR_STATUS,
    # Fields
    FIELD_POWER,
    FIELD_INSIDE,
    FIELD_OUTSIDE,
    FIELD_AUTO,
    FIELD_OUTSIDE_SENSOR_SAFETY_LOCK,
    FIELD_CMD_LOCKOUT,
    FIELD_AUTORETRACT,
    FIELD_TOTAL_OPEN_CYCLES,
    FIELD_TOTAL_AUTO_RETRACTS,
    FIELD_SETTINGS,
    FIELD_NOTIFICATIONS,
    FIELD_TZ,
    FIELD_SCHEDULE,
    FIELD_SCHEDULES,
    FIELD_INDEX,
    FIELD_ENABLED,
    FIELD_DAYSOFWEEK,
    FIELD_INSIDE_PREFIX,
    FIELD_OUTSIDE_PREFIX,
    FIELD_START_TIME_SUFFIX,
    FIELD_END_TIME_SUFFIX,
    FIELD_HOUR,
    FIELD_MINUTE,
    FIELD_VOLTAGE,
    FIELD_HOLD_TIME,
    FIELD_HOLD_OPEN_TIME,
    FIELD_SENSOR_TRIGGER_VOLTAGE,
    FIELD_SLEEP_SENSOR_TRIGGER_VOLTAGE,
    FIELD_DOOR_STATUS,
    FIELD_SUCCESS,
    FIELD_FWINFO,
    FIELD_BATTERY_PERCENT,
    FIELD_BATTERY_PRESENT,
    FIELD_AC_PRESENT,
    FIELD_HW_VERSION,
    FIELD_HW_REVISION,
    FIELD_FW_MAJOR,
    FIELD_FW_MINOR,
    FIELD_FW_PATCH,
    FIELD_SENSOR_ON_INDOOR_NOTIFICATIONS,
    FIELD_SENSOR_OFF_INDOOR_NOTIFICATIONS,
    FIELD_SENSOR_ON_OUTDOOR_NOTIFICATIONS,
    FIELD_SENSOR_OFF_OUTDOOR_NOTIFICATIONS,
    FIELD_LOW_BATTERY_NOTIFICATIONS,
    # Door states
    DOOR_STATE_IDLE,
    DOOR_STATE_CLOSED,
    DOOR_STATE_HOLDING,
    DOOR_STATE_KEEPUP,
    DOOR_STATE_RISING,
    DOOR_STATE_SLOWING,
    DOOR_STATE_CLOSING_TOP_OPEN,
    DOOR_STATE_CLOSING_MID_OPEN,
    # Commands
    CMD_OPEN,
    CMD_OPEN_AND_HOLD,
    CMD_CLOSE,
    CMD_GET_SETTINGS,
    CMD_GET_SENSORS,
    CMD_GET_POWER,
    CMD_GET_AUTO,
    CMD_GET_OUTSIDE_SENSOR_SAFETY_LOCK,
    CMD_GET_CMD_LOCKOUT,
    CMD_GET_AUTORETRACT,
    CMD_GET_DOOR_STATUS,
    CMD_GET_DOOR_OPEN_STATS,
    CMD_DISABLE_INSIDE,
    CMD_ENABLE_INSIDE,
    CMD_DISABLE_OUTSIDE,
    CMD_ENABLE_OUTSIDE,
    CMD_DISABLE_AUTO,
    CMD_ENABLE_AUTO,
    CMD_DISABLE_OUTSIDE_SENSOR_SAFETY_LOCK,
    CMD_ENABLE_OUTSIDE_SENSOR_SAFETY_LOCK,
    CMD_DISABLE_CMD_LOCKOUT,
    CMD_ENABLE_CMD_LOCKOUT,
    CMD_DISABLE_AUTORETRACT,
    CMD_ENABLE_AUTORETRACT,
    CMD_POWER_ON,
    CMD_POWER_OFF,
    CMD_GET_HW_INFO,
    CMD_GET_DOOR_BATTERY,
    CMD_HAS_REMOTE_ID,
    CMD_HAS_REMOTE_KEY,
    CMD_CHECK_RESET_REASON,
    CMD_GET_NOTIFICATIONS,
    CMD_SET_NOTIFICATIONS,
    CMD_GET_HOLD_TIME,
    CMD_SET_HOLD_TIME,
    CMD_GET_TIMEZONE,
    CMD_SET_TIMEZONE,
    CMD_GET_SENSOR_TRIGGER_VOLTAGE,
    CMD_SET_SENSOR_TRIGGER_VOLTAGE,
    CMD_GET_SLEEP_SENSOR_TRIGGER_VOLTAGE,
    CMD_SET_SLEEP_SENSOR_TRIGGER_VOLTAGE,
    CMD_GET_SCHEDULE_LIST,
    CMD_SET_SCHEDULE_LIST,
    CMD_GET_SCHEDULE,
    CMD_SET_SCHEDULE,
    CMD_DELETE_SCHEDULE,
    # Priorities
    PRIORITY_CRITICAL,
    PRIORITY_HIGH,
    PRIORITY_MEDIUM,
    PRIORITY_LOW,
    COMMAND_PRIORITIES,
)

# Import Home Assistant constants
from homeassistant.const import (
    CONF_NAME,
    CONF_HOST,
    CONF_PORT,
    CONF_ICON,
    CONF_ID,
    CONF_TIMEOUT,
    ATTR_ENTITY_ID,
)

# Home Assistant integration domain
DOMAIN = "powerpetdoor"

# HA-specific configuration keys
CONF_REFRESH = "refresh"
CONF_UPDATE = "update"
CONF_KEEP_ALIVE = "keep_alive"
CONF_RECONNECT = "reconnect"
CONF_HOLD_MIN = "hold_min"
CONF_HOLD_MAX = "hold_max"
CONF_HOLD_STEP = "hold_step"

# HA-specific state attributes
STATE_LAST_CHANGE = "last_change"
STATE_BATTERY_CHARGING = "battery_charging"
STATE_BATTERY_DISCHARGING = "battery_discharging"

# Default configuration values
DEFAULT_NAME = "Power Pet Door"
DEFAULT_PORT = 3000
DEFAULT_CONNECT_TIMEOUT = 10.0
DEFAULT_RECONNECT_TIMEOUT = 5.0
DEFAULT_KEEP_ALIVE_TIMEOUT = 30.0
DEFAULT_REFRESH_TIMEOUT = 300.0

# These values mirror the app. Though the actual value can be a MUCH broader range.
DEFAULT_HOLD_MIN = 2
DEFAULT_HOLD_MAX = 8
DEFAULT_HOLD_STEP = 2

# Service constants
SERVICE_UPDATE_SCHEDULE = "update_schedule"

# Attribute constants
ATTR_SCHEDULE = "schedule"
ATTR_SCHEDULE_ENTRIES = "schedule_entries"
ATTR_SCHEDULE_COUNT = "schedule_count"

# Validation regexes
ValidIpAddressRegex = r"^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$"
ValidHostnameRegex = r"^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$"
ValidTZRegex = r"^$"
