#!/usr/bin/env python3
"""Generate a testing gaps report from coverage.json.

This script reads the coverage report generated by pytest-cov and produces
a markdown report of current coverage status. The output replaces
tests/TESTING_GAPS.md with an up-to-date snapshot.

Usage:
    pytest --cov --cov-report=json
    python scripts/generate_gaps_report.py

Output:
    Writes directly to tests/TESTING_GAPS.md (or prints to stdout if --stdout).
"""

import ast
import io
import json
import os
import re
import sys
import tokenize
import tomllib
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path

SOURCE_PREFIX = "custom_components/powerpetdoor/"
PYPROJECT = Path("pyproject.toml")

#: Human-readable gloss for each configured exclusion pattern. Anything
#: without an entry is still reported, just without the explanation, so a
#: new pattern can never go undisclosed.
_EXCLUSION_NOTES = {
    "#\\s*pragma:\\s*no\\s+cover\\s*($|\\()": (
        "Explicitly annotated lines (see Pragma Exclusions below)"
    ),
    "^\\s*def __repr__": "String representation methods",
    "^\\s*raise NotImplementedError": "Abstract method stubs",
    "^\\s*if TYPE_CHECKING:": "Type-checking-only imports",
    "^\\s*if __name__ == .__main__.:": "Script entry-point guards",
    "^\\s*@overload\\s*$": "Typing overload declarations",
    "(^\\s*\\.\\.\\.\\s*$)|(:\\s*\\.\\.\\.\\s*$)": "Ellipsis stub bodies",
}
#: Gloss for each configured omit pattern.
_OMIT_NOTES = {
    "*/__init__.py": "Package init files",
    "*/__main__.py": "Entry point files",
}
#: Gloss for each configured branch-exclusion pattern.
_PARTIAL_NOTES = {
    "#\\s*pragma:\\s*no\\s+branch\\s*($|\\()": (
        "Explicitly annotated partial branches (see Pragma Exclusions below)"
    ),
}


@dataclass(frozen=True)
class CoverageSettings:
    """The coverage gate's perimeter, as configured in ``pyproject.toml``.

    Six dimensions, not two. ``TESTING_GAPS.md`` disclosed ``omit`` and
    ``exclude_lines`` and nothing else, and no test read anything but their
    non-emptiness - so ``branch = false`` (which stops measuring all 2410
    branch destinations while the gate still prints ``100.00%`` and exits
    0), a ``source`` that quietly drops ``scripts``, and an eighth
    ``exclude_lines`` pattern that deletes a whole shipped function were
    each a silent one-line disarm of this project's central quality control
    (round-9 test-fanatic H1). Reading them all here is what lets
    ``tests/test_gaps_report.py`` assert their *values* and lets the report
    disclose them.
    """

    source: list[str] = field(default_factory=list)
    omit: list[str] = field(default_factory=list)
    branch: bool = False
    fail_under: float = 0.0
    exclude_lines: list[str] = field(default_factory=list)
    partial_branches: list[str] = field(default_factory=list)


def coverage_config() -> CoverageSettings:
    """Read the configured coverage perimeter from pyproject.

    The report used to hard-code six bullets while the config carried seven
    patterns, so the project's own gap-disclosure artifact did not disclose
    the exclusion that mattered most (round-6 test-fanatic M2). Reading the
    config means the two cannot drift.
    """
    if not PYPROJECT.exists():
        return CoverageSettings()
    config = tomllib.loads(PYPROJECT.read_text())
    coverage = config.get("tool", {}).get("coverage", {})
    run = coverage.get("run", {})
    report = coverage.get("report", {})
    return CoverageSettings(
        source=list(run.get("source", [])),
        omit=list(run.get("omit", [])),
        branch=bool(run.get("branch", False)),
        fail_under=float(report.get("fail_under", 0)),
        exclude_lines=list(report.get("exclude_lines", [])),
        partial_branches=list(report.get("partial_branches", [])),
    )


#: Branches knowingly left uncovered, with the reason. Declared here rather
#: than marked in the source, because the card's coverage runs under V8
#: (`tests/frontend/jest.config.js` sets `coverageProvider: 'v8'`) and V8
#: coverage does not read `/* istanbul ignore */` hints - those are a
#: babel-plugin-istanbul feature, and adding babel would mean instrumenting
#: the card rather than running the exact bytes that ship.
#:
#: An entry here is a promise that the branch cannot be reached, not that
#: covering it was inconvenient.
ACKNOWLEDGED_GAPS: list[dict[str, str]] = [
    {
        "where": "www/powerpetdoor-schedule-card.js - t(), the `if (!text) text = key`",
        "why": (
            "Unreachable from any input. Every `t()` call site passes a "
            "literal key, and `scripts/check_translations.py` fails the "
            "build on a key that is not in the table, so no user action and "
            "no device response can reach it. Kept because the alternative "
            "when it IS wrong is rendering `undefined` into the card, which "
            "is worse for the user than showing the key."
        ),
    },
]


def render_acknowledged_gaps() -> list[str]:
    """Render the deliberately-uncovered branches and their reasons."""
    if not ACKNOWLEDGED_GAPS:
        return ["_None._"]
    out = []
    for gap in ACKNOWLEDGED_GAPS:
        out.append(f"- **{gap['where']}**")
        out.append(f"  {gap['why']}")
    return out


def render_automatic_exclusions() -> list[str]:
    """Render the "Automatic Exclusions" bullets from the live config."""
    settings = coverage_config()
    bullets = []
    for patterns, notes in (
        (settings.omit, _OMIT_NOTES),
        (settings.exclude_lines, _EXCLUSION_NOTES),
        (settings.partial_branches, _PARTIAL_NOTES),
    ):
        for entry in patterns:
            note = notes.get(entry)
            suffix = f" - {note}" if note else ""
            bullets.append(f"- `{entry}`{suffix}")
    return bullets


def render_gate_configuration() -> list[str]:
    """Render the three gate dimensions the exclusion bullets do not cover.

    ``branch``, ``source`` and ``fail_under`` decide what the 100% gate
    actually measures, and none of them appeared anywhere in this artifact -
    so `branch = true -> false` removed every one of 2410 branch
    destinations from the gate with the report still saying ``100.00%`` and
    nothing in the document changing (round-9 test-fanatic H1).
    """
    settings = coverage_config()
    if not settings.source:
        return []
    return [
        f"- Measured roots (`coverage.run.source`): {', '.join(f'`{s}`' for s in settings.source)}",
        f"- Branch coverage (`coverage.run.branch`): `{str(settings.branch).lower()}`",
        f"- Gate threshold (`coverage.report.fail_under`): `{settings.fail_under:g}`",
    ]


def _comment_tokens(source: str) -> dict[int, tuple[int, str]]:
    """Map line number -> (column, text) for every real comment in ``source``.

    Tokenizing rather than regexing raw lines matters as soon as more than
    one root is scanned: this generator's own report body contains the
    literal words "# pragma: no cover" inside string literals, and a raw
    regex reported them as the project's coverage exclusions.

    A file that will not tokenize (a syntax error) simply reports no
    pragmas rather than falling back to a scan that cannot tell code from
    text.
    """
    comments: dict[int, tuple[int, str]] = {}
    try:
        for token in tokenize.generate_tokens(io.StringIO(source).readline):
            if token.type == tokenize.COMMENT:
                comments[token.start[0]] = (token.start[1], token.string)
    except (tokenize.TokenError, SyntaxError, IndentationError):
        return {}
    return comments


def _string_spans(source: str) -> dict[int, list[tuple[int, int]]]:
    """Map line number -> column ranges occupied by string literals.

    Used to tell an ``exclude_lines`` pattern that matched *code* from one
    that matched *prose*. ``ast`` rather than ``tokenize`` because a
    docstring is one node spanning many lines and f-strings tokenize
    differently across the supported interpreters.

    A file that will not parse contributes nothing, exactly as
    :func:`_comment_tokens` reports no pragmas for one that will not
    tokenize.
    """
    spans: dict[int, list[tuple[int, int]]] = {}
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return {}
    for node in ast.walk(tree):
        is_str = isinstance(node, ast.Constant) and isinstance(node.value, str)
        if not (is_str or isinstance(node, ast.JoinedStr)):
            continue
        # `end_lineno`/`end_col_offset` are Optional in the stubs only
        # because ast nodes can be constructed by hand; ast.parse always
        # locates what it produces.
        assert node.end_lineno is not None and node.end_col_offset is not None
        for line in range(node.lineno, node.end_lineno + 1):
            start = node.col_offset if line == node.lineno else 0
            end = node.end_col_offset if line == node.end_lineno else len(source)
            spans.setdefault(line, []).append((start, end))
    return spans


def _statement_spans(source: str) -> list[tuple[int, int, bool]]:
    """``(first_line, last_line, is_docstring)`` for every statement.

    Coverage attributes a matched line to the statement *containing* it,
    so a phrase buried on line 5 of a nine-line dict literal excludes the
    whole assignment. The enclosing statement therefore has to be found by
    span, not by first line.

    ``is_docstring`` marks the case that costs nothing: coverage counts no
    statement inside a docstring, so a pattern matching prose there is
    untidy but removes nothing from the gate.
    """
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return []
    docstrings = {
        id(node.body[0])
        for node in ast.walk(tree)
        if isinstance(node, ast.Module | ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef)
        and node.body
        and isinstance(node.body[0], ast.Expr)
        and isinstance(node.body[0].value, ast.Constant)
        and isinstance(node.body[0].value.value, str)
    }
    return [
        (node.lineno, node.end_lineno or node.lineno, id(node) in docstrings)
        for node in ast.walk(tree)
        if isinstance(node, ast.stmt)
    ]


def _excludes_a_statement(spans: list[tuple[int, int, bool]], line: int) -> bool:
    """Whether excluding ``line`` would remove a statement from the gate."""
    enclosing = [span for span in spans if span[0] <= line <= span[1]]
    if not enclosing:
        return False
    innermost = min(enclosing, key=lambda span: span[1] - span[0])
    return not innermost[2]


def find_prose_exclusions(source_dirs: tuple[Path, ...], patterns: list[str]) -> list[dict]:
    """Find ``exclude_lines`` matches that landed in prose, not in code.

    Every ``exclude_lines`` entry is a ``re.search`` against the whole
    source line, so a bare phrase matches docstrings, f-strings and dict
    keys as readily as the construct it names. That has now removed
    statements from this project's 100% gate three rounds running - the
    bare ``...`` (round 6), a replacement comment that re-excluded the line
    it had just restored (round 7), and six bare phrases matching this
    file's own ``_EXCLUSION_NOTES`` table (round 8).

    A match is reported when it begins inside a string literal on a line
    that carries a real statement: that is precisely the case where the
    gate loses something it was measuring. A match inside a docstring is
    ignored, because coverage counts no statement there.

    Args:
        source_dirs: Roots inside the coverage gate.
        patterns: The configured ``exclude_lines`` entries.

    Returns:
        One dict per match, with ``file``, ``line``, ``pattern`` and
        ``code``, sorted by file then line.
    """
    compiled = [(pattern, re.compile(pattern)) for pattern in patterns]
    found: list[dict] = []
    for source_dir in source_dirs:
        for py_file in sorted(source_dir.rglob("*.py")):
            if py_file.name in ("__init__.py", "__main__.py"):
                continue
            try:
                source = py_file.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                continue
            spans = _string_spans(source)
            statements = None
            for number, text in enumerate(source.splitlines(), 1):
                if number not in spans:
                    continue
                for pattern, regex in compiled:
                    # Cheapest test first, then the span test, and only
                    # then the statement lookup - which is linear in the
                    # file's statement count and would otherwise run on
                    # every line of every gated file.
                    match = regex.search(text)
                    if not match:
                        continue
                    if not any(start <= match.start() < end for start, end in spans[number]):
                        continue
                    if statements is None:
                        statements = _statement_spans(source)
                    if not _excludes_a_statement(statements, number):
                        continue
                    found.append(
                        {
                            "file": str(py_file).replace(os.sep, "/"),
                            "line": number,
                            "pattern": pattern,
                            "code": text.strip(),
                        }
                    )
    return sorted(found, key=lambda entry: (entry["file"], entry["line"]))


def _collect_pragma_exclusions(source_dir: Path, root: Path | None = None) -> dict[str, list[dict]]:
    """Scan source files for pragma annotations and collect them.

    Args:
        source_dir: Directory to scan recursively.
        root: Directory the reported paths are relative to. Defaults to
            ``source_dir.parent.parent``, which is the repo root for the
            two-level ``custom_components/powerpetdoor``; a one-level root such as
            ``scripts`` passes its own parent.

    Returns a dict mapping relative file paths to lists of pragma entries,
    each with 'line', 'end_line', 'pragma_type', 'reason', and 'code'.
    """
    base = source_dir.parent.parent if root is None else root
    pragma_re = re.compile(r"#\s*pragma:\s*no\s+(cover|branch)")
    # Matched separately against the tail so the reason can contain its own
    # parentheses: `([^)]+)` stopped at the first ')' and reported two of
    # this project's own pragmas as "defensive: enable(" and "bound after
    # start(" (R4-L2). Anchored at both ends, and applied only to the tail,
    # so a line with trailing text after the parens keeps its pragma and
    # simply reports no reason rather than disappearing from the report.
    reason_re = re.compile(r"^\s*\((.+)\)\s*$")
    exclusions: dict[str, list[dict]] = {}

    for py_file in sorted(source_dir.rglob("*.py")):
        rel_path = os.path.relpath(py_file, base).replace(os.sep, "/")
        # Skip __init__.py and __main__.py (excluded from coverage entirely)
        if py_file.name in ("__init__.py", "__main__.py"):
            continue

        try:
            source = py_file.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        file_lines = source.splitlines()
        comments = _comment_tokens(source)

        # Track last pragma for grouping consecutive lines of the same type
        last_line_num = 0
        last_pragma_type = ""

        for i, line in enumerate(file_lines, start=1):
            comment = comments.get(i)
            if comment is None:
                continue
            column, text = comment
            match = pragma_re.search(text)
            if not match:
                continue

            pragma_type = match.group(1)  # "cover" or "branch"
            reason_match = reason_re.match(text[match.end() :])
            reason = reason_match.group(1).strip() if reason_match else ""

            # Group consecutive lines with the same pragma type
            if (
                rel_path in exclusions
                and exclusions[rel_path]
                and i == last_line_num + 1
                and pragma_type == last_pragma_type
            ):
                # Extend the existing range
                entry = exclusions[rel_path][-1]
                entry["end_line"] = i
                # Inherit reason from first line if this line has none
                if reason and not entry["reason"]:
                    entry["reason"] = reason
                last_line_num = i
                continue

            last_line_num = i
            last_pragma_type = pragma_type

            code = line.strip()
            # Remove the pragma comment itself for cleaner display, cutting
            # at the comment token's own column rather than searching the
            # line for a literal "# pragma:" (the regex also accepts
            # "#pragma:" and "#  pragma:").
            code_before_pragma = line[:column].strip()

            entry = {
                "line": i,
                "end_line": i,
                "pragma_type": pragma_type,
                "reason": reason,
                "code": code_before_pragma if code_before_pragma else code,
            }
            exclusions.setdefault(rel_path, []).append(entry)

    return exclusions


def _group_lines(lines: list[int]) -> str:
    """Group consecutive line numbers into ranges for readability."""
    if not lines:
        return ""
    ranges = []
    start = end = lines[0]
    for line in lines[1:]:
        if line == end + 1:
            end = line
        else:
            ranges.append(str(start) if start == end else f"{start}-{end}")
            start = end = line
    ranges.append(str(start) if start == end else f"{start}-{end}")
    return ", ".join(ranges)


def _categorize(path: str) -> str:
    """Categorize a source file path into a logical group."""
    p = path.replace(SOURCE_PREFIX, "")

    if p.startswith("simulator/commands/"):
        return "Simulator Commands"
    if p in ("simulator/cli.py", "simulator/ctl.py", "simulator/prompt_common.py"):
        return "Simulator CLI"
    if p.startswith("simulator/"):
        return "Simulator"
    return "Core Library"


def _stale_against_sources(coverage_file: Path) -> str | None:
    """Name a source file newer than the coverage data, if there is one.

    A report carries `datetime.now()` as its "Last updated", so running the
    generator against an old `coverage.json` produces a fresh-looking file
    full of stale numbers - which is worse than an obviously old one,
    because the timestamp invites trust. That happened: a report stamped
    2026-08-25 claimed 75.93% line coverage from data measured on the 23rd,
    when the suite was actually at 100%.

    `pytest --cov` alone does NOT write coverage.json; it needs
    `--cov-report=json`, which is easy to leave off. CI gets this right (it
    runs `coverage json` in the same job, immediately before), so this only
    ever fires locally - which is exactly where it is needed.
    """
    measured = coverage_file.stat().st_mtime
    for source in Path("custom_components").rglob("*.py"):
        if source.stat().st_mtime > measured:
            return str(source)
    return None


def main() -> int:
    """Generate and output the testing gaps report."""
    coverage_file = Path("coverage.json")
    stdout_mode = "--stdout" in sys.argv

    if not coverage_file.exists():
        msg = (
            "# Testing Gaps Report\n\n"
            "**Error**: No `coverage.json` found.\n\n"
            "Run `pytest --cov --cov-report=json` first to generate coverage data.\n"
        )
        if stdout_mode:
            print(msg)
        else:
            Path("tests/TESTING_GAPS.md").write_text(msg.rstrip("\n") + "\n")
        return 1

    newer = _stale_against_sources(coverage_file)
    if newer is not None:
        print(
            f"FAIL: coverage.json is older than {newer}, so this report would "
            "carry today's date on stale numbers. Re-run:\n"
            "    uv run pytest --cov --cov-report=json",
            file=sys.stderr,
        )
        return 1

    with open(coverage_file) as f:
        data = json.load(f)

    totals = data.get("totals", {})
    percent_covered = totals.get("percent_covered", 0)
    covered_lines = totals.get("covered_lines", 0)
    missing_lines = totals.get("missing_lines", 0)
    total_lines = covered_lines + missing_lines
    covered_branches = totals.get("covered_branches", 0)
    missing_branches = totals.get("missing_branches", 0)
    total_branches = covered_branches + missing_branches
    branch_pct = (covered_branches / total_branches * 100) if total_branches else 100.0

    lines = []
    lines.append("# Testing Gaps Report")
    lines.append("")
    lines.append("This file is **auto-generated** by CI after each test run. Do not edit manually.")
    lines.append("")
    lines.append(f"**Last updated:** {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append("")

    # Summary table
    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Line Coverage | {percent_covered:.2f}% |")
    lines.append(f"| Branch Coverage | {branch_pct:.2f}% |")
    lines.append(f"| Lines Covered | {covered_lines:,} / {total_lines:,} |")
    lines.append(f"| Branches Covered | {covered_branches:,} / {total_branches:,} |")
    lines.append(f"| Lines Missing | {missing_lines:,} |")
    lines.append("")

    # Collect all files and categorize
    all_files = []
    files_with_gaps = []
    for filepath, file_data in data.get("files", {}).items():
        summary = file_data.get("summary", {})
        file_percent = summary.get("percent_covered", 100)
        stmts = summary.get("num_statements", 0)
        num_branches = summary.get("num_branches", 0)
        file_info = {
            "path": filepath.replace(SOURCE_PREFIX, ""),
            "full_path": filepath,
            "percent": file_percent,
            "stmts": stmts,
            "branches": num_branches,
            "covered": summary.get("covered_lines", 0),
            "missing": summary.get("missing_lines", 0),
            "missing_line_numbers": file_data.get("missing_lines", []),
            "missing_branch_numbers": file_data.get("missing_branches", []),
            "category": _categorize(filepath),
        }
        all_files.append(file_info)
        if file_percent < 100:
            files_with_gaps.append(file_info)

    # Group by category for summary
    categories: dict[str, list] = {}
    for f in all_files:
        categories.setdefault(f["category"], []).append(f)

    # Category summary
    lines.append("## Coverage by Category")
    lines.append("")
    lines.append("| Category | Files | Coverage | Status |")
    lines.append("|----------|-------|----------|--------|")

    for cat_name in sorted(categories.keys()):
        cat_files = categories[cat_name]
        cat_stmts = sum(f["stmts"] for f in cat_files)
        cat_covered = sum(f["covered"] for f in cat_files)
        cat_pct = (cat_covered / cat_stmts * 100) if cat_stmts else 100.0
        cat_gaps = sum(1 for f in cat_files if f["percent"] < 100)
        status = ":green_circle:" if cat_pct >= 99.5 else ":yellow_circle:"
        gap_note = f" ({cat_gaps} with gaps)" if cat_gaps else ""
        lines.append(f"| {cat_name} | {len(cat_files)}{gap_note} | {cat_pct:.1f}% | {status} |")

    lines.append("")

    if not files_with_gaps:
        lines.append("## Status: 100% Coverage :green_circle:")
        lines.append("")
        lines.append("All code is covered by tests. No gaps to report.")
        lines.append("")
    else:
        files_with_gaps.sort(key=lambda x: x["percent"])

        lines.append(f"## Current Gaps ({len(files_with_gaps)} files)")
        lines.append("")
        lines.append("| Module | Stmts | Missing | Coverage |")
        lines.append("|--------|-------|---------|----------|")

        for fi in files_with_gaps:
            lines.append(
                f"| `{fi['path']}` | {fi['stmts']} | {fi['missing']} | {fi['percent']:.1f}% |"
            )

        lines.append("")
        lines.append("### Missing Lines Detail")
        lines.append("")

        for fi in files_with_gaps:
            if fi["missing_line_numbers"]:
                lines.append(f"**`{fi['path']}`**: {_group_lines(fi['missing_line_numbers'])}")
                lines.append("")

    # Collect pragma exclusions from every root inside the coverage gate.
    # scripts/ joined coverage.run.source and has its own report category,
    # so a pragma added there must show up here too (T1).
    pragma_exclusions: dict[str, list[dict]] = {}
    for source_dir in (Path(SOURCE_PREFIX),):
        if source_dir.exists():
            pragma_exclusions.update(_collect_pragma_exclusions(source_dir, root=Path()))

    # Pragma exclusions section
    lines.append("## Coverage Exclusions")
    lines.append("")
    lines.append("### Gate Configuration")
    lines.append("")
    lines.append(
        "What the 100% gate measures, read from `pyproject.toml` "
        "(`tests/test_gaps_report.py` asserts each value):"
    )
    lines.append("")
    lines.extend(render_gate_configuration())
    lines.append("")
    lines.append("### Automatic Exclusions")
    lines.append("")
    lines.append("The following are excluded from coverage by configuration (`pyproject.toml`):")
    lines.append("")
    # Rendered from the live config, never hand-maintained (M2).
    lines.extend(render_automatic_exclusions())
    lines.append("")

    lines.append("### Acknowledged Gaps")
    lines.append("")
    lines.append(
        "Branches knowingly left uncovered. These are NOT configuration "
        "exclusions - the gate still counts them - and each one is a claim "
        "that the branch cannot be reached, with the reason why:"
    )
    lines.append("")
    lines.extend(render_acknowledged_gaps())
    lines.append("")

    # Every pattern above is a `re.search` against the whole source line,
    # so one can silently exclude a statement it merely *mentions*. This
    # section is the gate's real perimeter as opposed to its intended one:
    # an entry here means a statement left the 100% gate because a pattern
    # matched a string literal rather than the construct it names.
    _settings = coverage_config()
    prose = find_prose_exclusions(
        (Path(SOURCE_PREFIX),),
        # Both halves of the same mechanism: `partial_branches` is the
        # identical bare-`re.search` hazard applied to branch arcs, and the
        # sweep was simply never handed it.
        _settings.exclude_lines + _settings.partial_branches,
    )
    lines.append("### Prose-Triggered Exclusions")
    lines.append("")
    if prose:
        lines.append(
            f"**{len(prose)} statement(s)** are excluded because an `exclude_lines` "
            "or `partial_branches` pattern matched prose (a string literal), not the "
            "construct it names. These are unintended and are outside the 100% gate."
        )
        lines.append("")
        lines.append("| File | Line | Pattern | Code |")
        lines.append("|------|------|---------|------|")
        for entry in prose:
            code = entry["code"].replace("|", "\\|")
            pattern = entry["pattern"].replace("|", "\\|")
            lines.append(f"| `{entry['file']}` | {entry['line']} | `{pattern}` | `{code}` |")
    else:
        lines.append(
            "None. Every `exclude_lines` and `partial_branches` pattern above matches "
            "only the construct it names, never a string literal on a line carrying a "
            "statement."
        )
    lines.append("")

    if pragma_exclusions:
        total_pragma_lines = 0
        total_pragma_entries = 0
        for entries in pragma_exclusions.values():
            total_pragma_entries += len(entries)
            for e in entries:
                total_pragma_lines += e["end_line"] - e["line"] + 1

        lines.append("### Pragma Exclusions")
        lines.append("")
        lines.append(
            f"**{total_pragma_lines} lines** across **{len(pragma_exclusions)} files** "
            f"in **{total_pragma_entries} annotations** "
            f"are excluded via `# pragma: no cover` or `# pragma: no branch`."
        )
        lines.append("")

        for filepath in sorted(pragma_exclusions.keys()):
            entries = pragma_exclusions[filepath]
            short_path = filepath.replace(SOURCE_PREFIX, "")
            file_lines_count = sum(e["end_line"] - e["line"] + 1 for e in entries)
            lines.append(f"#### `{short_path}` ({file_lines_count} lines)")
            lines.append("")
            lines.append("| Lines | Type | Reason | Code |")
            lines.append("|-------|------|--------|------|")

            for entry in entries:
                if entry["end_line"] > entry["line"]:
                    line_ref = f"{entry['line']}-{entry['end_line']}"
                else:
                    line_ref = str(entry["line"])
                ptype = f"no {entry['pragma_type']}"
                reason = entry["reason"] if entry["reason"] else "*no reason given*"
                # Escape pipe characters in code for markdown table
                code = entry["code"].replace("|", "\\|")
                lines.append(f"| {line_ref} | {ptype} | {reason} | `{code}` |")

            lines.append("")
    else:
        lines.append("### Pragma Exclusions")
        lines.append("")
        lines.append("No `# pragma: no cover` or `# pragma: no branch` annotations found.")
        lines.append("")

    output = "\n".join(lines) + "\n"

    if stdout_mode:
        print(output, end="")
    else:
        Path("tests/TESTING_GAPS.md").write_text(output.rstrip("\n") + "\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
